// fifo.v

// Generated using ACDS version 20.1 177

`timescale 1 ps / 1 ps
module fifo (
		input  wire [7:0] data,  //  fifo_input.datain
		input  wire       wrreq, //            .wrreq
		input  wire       rdreq, //            .rdreq
		input  wire       clock, //            .clk
		input  wire       sclr,  //            .sclr
		output wire [7:0] q,     // fifo_output.dataout
		output wire [8:0] usedw, //            .usedw
		output wire       full,  //            .full
		output wire       empty  //            .empty
	);

	fifo_fifo_1910_kp32l7y fifo_0 (
		.data  (data),  //   input,  width = 8,  fifo_input.datain
		.wrreq (wrreq), //   input,  width = 1,            .wrreq
		.rdreq (rdreq), //   input,  width = 1,            .rdreq
		.clock (clock), //   input,  width = 1,            .clk
		.sclr  (sclr),  //   input,  width = 1,            .sclr
		.q     (q),     //  output,  width = 8, fifo_output.dataout
		.usedw (usedw), //  output,  width = 9,            .usedw
		.full  (full),  //  output,  width = 1,            .full
		.empty (empty)  //  output,  width = 1,            .empty
	);

endmodule
